### PR TITLE
Checkbox default value set to true instead of 1

### PR DESCRIPTION
**Pull request by emaglio**
As per issue https://github.com/trailblazer/formular/issues/41 maybe makes more sense to have true as default value instead of 1. For  custom control value is still 1.

### CODE REVIEW

**Comment by Titinux** [comment]
Maybe default_unchecked_value should return false as well ? Just to be consistent.

**Comment by fran-worley** [comment]
I'm torn about this, the rails form helper defaults to 1 for the value (which is truthy anyway). @Titinux any reason why you use the literal `true` instead of 1/0 ?

**Comment by Titinux** [comment]
Using literal true in the form is not the starting point. In rails/simple_form when your define your checkbox and your data is truthy the checkbox is checked with formular it's not the case. I'm perfectly fine with 0/1 in html forms.

Currently if I do
```ruby
f.checkbox(:is_public)
```
and if is_public is true or false the checkbox is never checked.
We can keep 1/0 in html but element checkbox should react to truthy values (1/true/"true")

**Comment by fran-worley** [comment]
@Titinux this is more along the lines of what I was thinking

**Pull request closed without merging**
